/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for qat_rsaprivkey
 */
#ifdef QAT_PKE_OLD_SUPPORTED
#include <linux/version.h>
#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,4,0)
#include <linux/asn1_ber_bytecode.h>
#include "qat_rsaprivkey-asn1.h"

enum qat_rsaprivkey_actions {
	ACT_qat_rsa_get_d = 0,
	ACT_qat_rsa_get_e = 1,
	ACT_qat_rsa_get_n = 2,
	NR__qat_rsaprivkey_actions = 3
};

static const asn1_action_t qat_rsaprivkey_action_table[NR__qat_rsaprivkey_actions] = {
	[   0] = qat_rsa_get_d,
	[   1] = qat_rsa_get_e,
	[   2] = qat_rsa_get_n,
};

static const unsigned char qat_rsaprivkey_machine[] = {
	// RsaPrivKey
	[   0] = ASN1_OP_MATCH,
	[   1] = _tag(UNIV, CONS, SEQ),
	[   2] =  ASN1_OP_MATCH,		// version
	[   3] =  _tag(UNIV, PRIM, INT),
	[   4] =  ASN1_OP_MATCH_ACT,		// n
	[   5] =  _tag(UNIV, PRIM, INT),
	[   6] =  _action(ACT_qat_rsa_get_n),
	[   7] =  ASN1_OP_MATCH_ACT,		// e
	[   8] =  _tag(UNIV, PRIM, INT),
	[   9] =  _action(ACT_qat_rsa_get_e),
	[  10] =  ASN1_OP_MATCH_ACT,		// d
	[  11] =  _tag(UNIV, PRIM, INT),
	[  12] =  _action(ACT_qat_rsa_get_d),
	[  13] =  ASN1_OP_MATCH,		// prime1
	[  14] =  _tag(UNIV, PRIM, INT),
	[  15] =  ASN1_OP_MATCH,		// prime2
	[  16] =  _tag(UNIV, PRIM, INT),
	[  17] =  ASN1_OP_MATCH,		// exponent1
	[  18] =  _tag(UNIV, PRIM, INT),
	[  19] =  ASN1_OP_MATCH,		// exponent2
	[  20] =  _tag(UNIV, PRIM, INT),
	[  21] =  ASN1_OP_MATCH,		// coefficient
	[  22] =  _tag(UNIV, PRIM, INT),
	[  23] = ASN1_OP_END_SEQ,
	[  24] = ASN1_OP_COMPLETE,
};

const struct asn1_decoder qat_rsaprivkey_decoder = {
	.machine = qat_rsaprivkey_machine,
	.machlen = sizeof(qat_rsaprivkey_machine),
	.actions = qat_rsaprivkey_action_table,
};
#endif
#endif
